### ISSUE TITLE
Thoughts on layout / design

### ISSUE THREAD

**Issue by deidyomega** [CodeForFoco/CERP-webview#10]
For those of us who know design, does anyone want to create a wireframe so we can start talking about how this site should look?

@abettermap You mentioned your mad skills could be used here

**Comment by abettermap** [comment]
Ha! Not with designing from scratch really, buuuut if somebody else does it I can code it in SCSS.

I'll give it a whirl if there are no takers, though.

**Comment by deidyomega** [comment]
I was referring to just talking about general site layout.

What kind of interface do we want?  Map Centeric, What should the landing page be?  

How about user engagement?

Matt

**Comment by abettermap** [comment]
🗺 🗺 🗺 for landing.  

But I might be a little biased 😉
