### ISSUE TITLE
Getting Started (README.md)

### ISSUE THREAD

**Issue by deidyomega** [CodeForFoco/CERP-webview#11]
Verify Required Applications

If you aren't using node 6.11.4 and npm@3.10.10, your project may not build correctly. If that is the case, consider using nvm or Docker as an alternative to actually installing a different version of Node on your machine.

@abettermap Could you rewrite this on how to use nvm to make this project run.

Believe You just did `nvm use` and it correctly grabbed the version from the .nvmrc file.

**Comment by abettermap** [comment]
Sure thing, should have time this morning.
